// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['app']['App']['Close']();
}

export function DeleteTimeSlot(arg1) {
  return window['go']['app']['App']['DeleteTimeSlot'](arg1);
}

export function GetActiveTimeSlot() {
  return window['go']['app']['App']['GetActiveTimeSlot']();
}

export function GetElapsedTime() {
  return window['go']['app']['App']['GetElapsedTime']();
}

export function GetTaskStatistics(arg1) {
  return window['go']['app']['App']['GetTaskStatistics'](arg1);
}

export function GetTimeSlotsByDate(arg1) {
  return window['go']['app']['App']['GetTimeSlotsByDate'](arg1);
}

export function IsTimerRunning() {
  return window['go']['app']['App']['IsTimerRunning']();
}

export function StartTimer(arg1) {
  return window['go']['app']['App']['StartTimer'](arg1);
}

export function StopTimer() {
  return window['go']['app']['App']['StopTimer']();
}

export function UpdateTimeSlot(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UpdateTimeSlot'](arg1, arg2, arg3, arg4);
}
