// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Close():Promise<void>;

export function DeleteTimeSlot(arg1:number):Promise<void>;

export function GetActiveTimeSlot():Promise<models.TimeSlot>;

export function GetElapsedTime():Promise<number>;

export function GetTaskStatistics(arg1:string):Promise<Record<string, number>>;

export function GetTimeSlotsByDate(arg1:string):Promise<Array<models.TimeSlot>>;

export function IsTimerRunning():Promise<boolean>;

export function StartTimer(arg1:string):Promise<models.TimeSlot>;

export function StopTimer():Promise<models.TimeSlot>;

export function UpdateTimeSlot(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;
